version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    restart: always
    networks:
      - easynode_net
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    restart: always
    networks:
      - easynode_net
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    restart: always
    networks:
      - easynode_net
    ports:
      - "9003:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - kafka
  mysql:
    image: bitnami/mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - easynode_net
    volumes:
      - ./mysql:/bitnami/mysql/data
    environment:
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
      - MYSQL_DATABASE=easynode
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=test12345678
  clickhouse:
    image: bitnami/clickhouse:23
    environment:
      - CLICKHOUSE_ADMIN_USER=test
      - CLICKHOUSE_ADMIN_PASSWORD=test
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_MYSQL_PORT=9004
      - CLICKHOUSE_POSTGRESQL_PORT=9005
      - CLICKHOUSE_INTERSERVER_HTTP_PORT=9009
    volumes:
      - ./clickhouse_data:/bitnami/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9005:9005"
      - "9009:9009"
    networks:
      - easynode_net
    depends_on:
      - zookeeper
  easynode:
    build:
      context: .
      dockerfile: ./docker-compose-single.yml
    ports:
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./easynode:/app
    depends_on:
      - kafka
      - mysql
      - clickhouse

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
   easynode_net:
     driver: bridge  
