package monitor

const (
	BlockNumberTable = "CREATE DATABASE IF NOT EXISTS %v;\nUSE %v;\nCREATE TABLE IF NOT EXISTS `%v` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `chain_code` int NOT NULL DEFAULT '100' COMMENT '公链代码',\n  `latest_number` bigint DEFAULT '0' COMMENT '区块链最新高度',\n  `recent_number` bigint DEFAULT '0' COMMENT '已经处理区块高度',\n  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `log_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `code` (`chain_code`) USING BTREE\n) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='公链最新区块高度表';"

	NodeErrorTable = "CREATE DATABASE IF NOT EXISTS %v;\nUSE %v;\nCREATE TABLE IF NOT EXISTS `%v` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `block_chain` int NOT NULL COMMENT '公链code',\n  `tx_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,\n  `block_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,\n  `block_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,\n  `source_type` tinyint DEFAULT '0' COMMENT '任务类型 1: 交易 2:区块 3.收据',\n  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `id` (`block_chain`,`tx_hash`,`block_hash`,`block_number`,`source_type`) USING BTREE,\n  KEY `type` (`source_type`) USING BTREE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='系统自检的异常数据表';"

	NodeInfoTable = "CREATE DATABASE IF NOT EXISTS %v;\nUSE %v;\nCREATE TABLE IF NOT EXISTS `%v` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ip',\n  `host` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'host',\n  `node_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '节点的唯一标识',\n  `info` json NOT NULL COMMENT '''采集节点的配置信息 ，一个json 对象 如：\\n[\\n  {\\n   \"blockchain\":\"eth\", \\n   \"block_code\":100,\\n   \"config\":{\\n              \"tx\": 0,\\n               \"block\":1\\n          }\\n  },\\n  {}\\n]'';',\n  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `node_id` (`node_id`) USING BTREE\n) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='节点信息表';"

	NodeSourceTable = "CREATE DATABASE IF NOT EXISTS %v;\nUSE %v;\nCREATE TABLE IF NOT EXISTS `%v` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `block_chain` int NOT NULL COMMENT '公链code',\n  `tx_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,\n  `block_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,\n  `block_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,\n  `source_type` tinyint DEFAULT '0' COMMENT '任务类型 1: 交易 2:区块 3.收据',\n  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `id` (`block_chain`,`tx_hash`,`block_hash`,`block_number`,`source_type`) USING BTREE,\n  KEY `type` (`source_type`,`block_chain`) USING BTREE\n) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务来源表\\n\\n1. 自产生 block number\\n2.重试任务: Tx, block\\n3. 收据任务';\n"

	NodeTaskTable = "CREATE DATABASE IF NOT EXISTS %v;\nUSE %v;\nCREATE TABLE IF NOT EXISTS  `%v` (\n  `node_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '节点的唯一标识',\n  `block_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '区块高度',\n  `block_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '区块hash',\n  `tx_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '交易hash',\n  `task_type` tinyint NOT NULL DEFAULT '0' COMMENT ' 0:保留 1:同步Tx 2:同步Block 3:同步收据',\n  `block_chain` int NOT NULL DEFAULT '100' COMMENT '公链code, 默认：100 (etc)',\n  `task_status` int DEFAULT '0' COMMENT '0: 初始 1: 成功. 2: 失败.  3: 执行中. 4:kafka 写入中 5:重试 其他：重试次数(5以上)',\n  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `log_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  PRIMARY KEY (`id`),\n  KEY `type` (`task_type`) USING BTREE,\n  KEY `status` (`task_status`) USING BTREE,\n  KEY `tx_hash` (`tx_hash`) USING BTREE,\n  KEY `block_number` (`block_number`) USING BTREE,\n  KEY `block_hash` (`block_hash`) USING BTREE,\n  KEY `block_chain` (`block_chain`) USING BTREE,\n  KEY `node_id` (`node_id`) USING BTREE\n) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='节点任务表';"
)
